export const EXPERIMENT_ALERTS = {
  autotransformerNotReady: {
    description: 'Ensure that the MCB is switched ON and the RLC values are selected before switching ON the autotransformer.',
    duration: 8000,
    icon: '⚠️',
    sound: 'autotransformerNotReady',
    target: '#autotransformer-panel',
    title: ' Autotransformer',
    type: 'warning',
  },
  connectionsVerified: {
    description: 'Connections verified successfully. Now turn ON the MCB by clicking the MCB lever.',
    duration: 8000,
    icon: '✅',
    sound: 'connectionsVerified',
    target: '#check-button',
    title: 'Connections Verified',
    type: 'success',
  },
  mcbOn: {
    description: 'MCB has been turned ON. Select the resistor, inductor, and capacitor values from the dropdowns.',
    duration: 8000,
    icon: '⚡',
    sound: 'mcbOn',
    target: '#mcb-supply',
    title: 'MCB ON',
    type: 'success',
  },
  componentValuesSelected: {
    description: 'Resistor, inductor, and capacitor values have been selected. Now click the power button of the autotransformer.',
    duration: 10000,
    icon: '✅',
    sound: 'componentValuesSelected',
    target: '#autotransformer-panel',
    title: 'Component Values Selected',
    type: 'success',
  },
  autotransformerOn: {
    description: 'Autotransformer is now ON. Next, click the autotransformer knob to set the voltage.',
    duration: 8000,
    icon: '🎛️',
    sound: 'autotransformerOn',
    target: '#autotransformer-panel',
    title: 'Autotransformer ON',
    type: 'success',
  },
  voltageSet: {
    description: 'The voltage has been set to 30 V to ensure safe operation of the RLC circuit experiment. The readings are now displayed on the voltmeters, ammeter, and wattmeter. Now click the Add button to add the readings to the observation table.',
    duration: 18000,
    icon: '⚡',
    sound: 'voltageSet',
    target: '#equipment-panel',
    title: 'Voltage Set to 30 V',
    type: 'success',
  },
  firstReadingAdded: {
    description: 'Reading 1 of 12 has been added. Select a different RLC combination and click the Add button again.',
    duration: 18000,
    icon: '✅',
    sound: 'firstReadingAdded',
    target: '#observation-table-panel',
    title: 'First Reading Added',
    type: 'success',
  },
  newRlcValueSelected: {
    description: 'A new RLC value is set. Click the Add button to record it.',
    duration: 8000,
    icon: '✅',
    sound: 'newRlcValueSelected',
    target: '#add-reading-button',
    title: 'New RLC Value Selected',
    type: 'success',
  },
  duplicateRlcCombination: {
    description: 'Select a different RLC combination to enable the Add button.',
    duration: 10000,
    icon: '⚠️',
    sound: 'duplicateRlcCombination',
    target: '#add-reading-button',
    title: 'RLC Combination Already Recorded',
    type: 'warning',
  
    // Prevent the same duplicate warning from being queued multiple times
    dedupeKey: 'duplicateRlcCombination',
    dedupeWindow: 2000,
  },
  secondReadingAdded: {
    description: 'Reading 2 of 12 has been added. Repeat the same steps until all 12 readings have been recorded.',
    duration: 12000,
    icon: '✅',
    sound: 'secondReadingAdded',
    target: '#observation-table-panel',
    title: 'Second Reading Added',
    type: 'success',
  },
  fifthReadingAdded: {
    description: '5th Reading added successfully. Now, select the reading you want to verify theoretically from the dropdown menu, or you can add more readings to the table.',
    duration: 18000,
    icon: '✅',
    sound: 'fifthReadingAdded',
    target: '#observation-table-panel',
    title: '5th Reading Added',
    type: 'success',
  },
  readingAdded: {
    duration: 12000,
    icon: '✅',
    target: '#observation-table-panel',
    title: 'Reading Added',
    type: 'success',
  },
  allReadingsRecorded: {
    description: 'All 12 readings have been recorded. Now, select the reading you want to verify theoretically from the dropdown menu and click the Verify button to verify the reading.',
    duration: 20000,
    icon: '📊',
    sound: 'allReadingsRecorded',
    target: '#theoretical-calculations-panel',
    title: 'All Readings Recorded',
    type: 'success',
  },
  maximumReadingsReached: {
    description: 'You can add a maximum of 12 readings to the table.',
    duration: 8000,
    icon: 'ℹ️',
    sound: 'maximumReadingsReached',
    target: '#observation-table-panel',
    title: 'Maximum Readings Reached',
    type: 'info',
  },
calculationsVerified: {
  description: 'Theoretical calculations verified successfully.',
  duration: 13000,
  icon: '✅',
  sound: 'calculationsVerified',
  target: '#theoretical-calculations-panel',
  title: 'Verified',
  type: 'success',
},
}
